[package]
name = "netcanv"
version = "0.5.0"
authors = ["liquidev <liquidev@tutanota.com>"]
description = "An online collaborative paint canvas."
repository = "https://github.com/liquidev/netcanv"
license = "Apache-2.0"

edition = "2021"

[workspace]
members = [
   "netcanv-renderer",
   "netcanv-renderer-opengl",
   "netcanv-relay",
   "netcanv-protocol",
]

[features]
default = ["renderer-opengl"]
renderer-opengl = ["netcanv-renderer-opengl"]

[dependencies]

# Common things
anyhow = "1.0.40"
heapless = { version = "0.7.7", default-features = false }
once_cell = "1.8.0"
strum = { version = "0.23.0", features = ["derive"] }

# Windowing and graphics
native-dialog = "0.5.5"
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
webp = { version = "0.2.0", features = ["img"] }
usvg = { version = "0.14.0", default-features = false }
resvg = { version = "0.14.0", default-features = false }
tiny-skia = { version = "0.5.0", default-features = false, features = ["std", "simd"] }

# Networking
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"

# Multithreading
nysa = "0.2.2"

# Utilities
directories = "3.0.2"
toml = "0.5.8"

# Clipboard
arboard = "2.0.1"

# Workspace
netcanv-renderer = { path = "netcanv-renderer" }
netcanv-renderer-opengl = { path = "netcanv-renderer-opengl", optional = true }
netcanv-protocol = { path = "netcanv-protocol" }

[profile.release]
lto = "fat"
