[package]
name = "netcanv"
version = "0.8.0"
authors = ["liquidev <liquidev@tutanota.com>"]
description = "An online collaborative paint canvas."
repository = "https://github.com/liquidev/netcanv"
license = "Apache-2.0"

edition = "2021"

[workspace]
members = [
   "netcanv-i18n",
   "netcanv-i18n-macros",
   "netcanv-renderer",
   "netcanv-renderer-opengl",
   "netcanv-relay",
   "netcanv-protocol",
]

[features]
default = ["renderer-opengl"]
renderer-opengl = ["netcanv-renderer-opengl"]

[dependencies]

# Common things
heapless = { version = "0.7.7", default-features = false }
once_cell = "1.8.0"
strum = { version = "0.23.0", features = ["derive"] }

# Logging
log = "0.4.14"
simple_logger = { version = "2.1.0", default-features = false, features = ["colors"] }

# Windowing and graphics
native-dialog = "0.5.5"
webbrowser = "0.5.5"
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
webp = { version = "0.2.0", features = ["img"] }
usvg = { version = "0.14.0", default-features = false }
resvg = { version = "0.14.0", default-features = false }
tiny-skia = { version = "0.5.0", default-features = false, features = ["std", "simd"] }

# Internationalization
sys-locale = "0.1.0"

# Networking
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
tokio = { version = "1.16.1", features = ["full"] }
tokio-tungstenite = { version = "0.16.1", features = ["rustls-tls-native-roots"] }

# Multithreading
nysa = "0.2.2"

# Utilities
directories = "3.0.2"
tempfile = "3.3.0"
toml = "0.5.8"
url = "2.2.2"
instant = "0.1.12"
futures-util = { version = "0.3", features = ["sink", "std"] }

# Clipboard
arboard = "2.0.1"

# Workspace
netcanv-renderer = { path = "netcanv-renderer" }
netcanv-renderer-opengl = { path = "netcanv-renderer-opengl", optional = true }
netcanv-protocol = { path = "netcanv-protocol" }

netcanv-i18n = { path = "netcanv-i18n" }

[profile.release]
lto = "fat"
