[package]
name = "netcanv-matchmaker"
version = "0.1.0"
edition = "2018"

[dependencies]

netcanv-protocol = { path = "../netcanv-protocol" }

serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
rand = "0.8.3"
crossbeam-channel = "0.4.4"
thiserror = "1.0.24"

