[package]
name = "netcanv-relay"
version = "2.1.0"
edition = "2021"

[dependencies]

netcanv-protocol = { path = "../netcanv-protocol" }

tokio = { version = "1.14.0", features = ["full"] }
tokio-tungstenite = "0.16.1"
futures-util = { version = "0.3", features = ["sink", "std"] }
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
bytemuck = "1.7.2"
nanorand = "0.6.1"
anyhow = "1.0.40"
structopt = "0.3.25"
log = "0.4.14"
simple_logger = "2.1.0"
