[package]
name = "netcanv-renderer-opengl"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
winit = "0.25.0"
glutin = "0.27.0"
glow = "0.11.0"
memoffset = "0.6.4"
lazy_static = "1.4.0"
freetype-rs = "0.28.0"
smallvec = { version = "1.7.0", features = ["const_generics"] }
glam = "0.19.0"

netcanv-renderer = { path = "../netcanv-renderer" }
